spring:
  application:
    name: icom-product
  data:
    mongodb:
      uri: mongodb://mongo:27017/icom
server:
  port: 8081

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true 
        serviceUrl:
            defaultZone: http://104.215.148.134:8761/eureka/,http://104.215.148.134:8762/eureka/
icom:
  amqp:
    rabbit:
      address : rabbitmq:5672
      username: guest
      password: guest
      vhost : /
      exchange : Icom-exchange
      queue: Icom-product-queue
axon:
  axonserver:
    servers: 23.97.51.103
